name: kart-env

services:
  dwc_haproxy:
    image: haproxy:lts-alpine
    # container_name: dwc_haproxy
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ../dwc/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    sysctls:
      - net.ipv4.ip_unprivileged_port_start=0
    networks:
      kart_net:
        aliases:
          - gamestats.gs.nintendowifi.net
          - gamestats2.gs.nintendowifi.net
          - mariokartwii.gamestats.gs.nintendowifi.net
          - mariokartwii.gamestats2.gs.nintendowifi.net
          - mariokartwii.sake.gs.nintendowifi.net
          - mariokartwii.available.gs.nintendowifi.net
          - naswii.nintendowifi.net
          - nas.nintendowifi.net
          - conntest.nintendowifi.net
          - nintendowifi.net

  dwc:
    build:
      context: ../dwc
    # container_name: dwc
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9001:9001"
      - "27500:27500"
      - "28910:28910"
      - "29900:29900"
      - "29901:29901"
      - "29920:29920"
      - "27900:27900/udp"
      - "27901:27901/udp"
    volumes:
      - ../dwc/data:/dwc/data
    networks:
      kart_net:
        aliases:
          - gpcm.gs.nintendowifi.net
          - gpsp.gs.nintendowifi.net
          - mariokartwii.master.gs.nintendowifi.net
          - mariokartwii.ms19.gs.nintendowifi.net
          - mariokartwii.natneg1.gs.nintendowifi.net
          - mariokartwii.natneg2.gs.nintendowifi.net
          - mariokartwii.natneg3.gs.nintendowifi.net
          - wiimmfi.de

  kart_env:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        dolphin-src: ../dolphin
    image: kart_env
    # container_name: kart_env
    ports:
      - "6080-6091:6080-6091" # Assume we use 12 clients in a container
    volumes:
      - ./src:/kart_env/src
      - ./main.py:/workspace/main.py
      - ../MarioKartWii.iso:/workspace/MarioKartWii.iso:ro
      - ./users:/workspace/users
    ipc: host
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    extra_hosts:
      - "gamestats.gs.nintendowifi.net:146.56.169.123"
      - "gamestats2.gs.nintendowifi.net:146.56.169.123"
      - "gpcm.gs.nintendowifi.net:146.56.169.123"
      - "gpsp.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.available.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.gamestats.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.gamestats2.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.master.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.ms19.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.natneg1.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.natneg2.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.natneg3.gs.nintendowifi.net:146.56.169.123"
      - "mariokartwii.sake.gs.nintendowifi.net:146.56.169.123"
      - "naswii.nintendowifi.net:146.56.169.123"
      - "nas.nintendowifi.net:146.56.169.123"
      - "nintendowifi.net:146.56.169.123"
      - "wiimmfi.de:146.56.169.123"
    networks:
      - kart_net

networks:
  kart_net:
    driver: bridge
