services:
  kart_env:
    build:
      context: .
      dockerfile: Dockerfile
      additional_contexts:
        dolphin-src: ../dolphin
    image: kart_env
    volumes:
      - ./src:/kart_env/src
      - ./main.py:/workspace/main.py
      - ../MarioKartWii.iso:/workspace/MarioKartWii.iso:ro
      - ./users:/workspace/users
      - ./states:/workspace/states
    shm_size: "6gb"
    ulimits:
      memlock: -1
      stack: 67108864
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
